Feature/network service
renatasiqueira/challenge-app-ios pull request #3
Opened 2022-10-11 09:06 UTC by renatasiqueira

2022-10-11 09:45 UTC, RubenAntunes16 approved these changes

2022-10-19 13:22 UTC, cpradobliss requested changes
Nice PR in general! ⭐️

There are some details that need to be updated, however. Please take a look at the comments added to the PR.

2022-10-19 13:22 UTC, cpradobliss commented on EmojisApp/MainCoordinator.swift
> +        navigationController?.viewControllers.forEach {
Updating your controllers in a for - in most cases - will be considered a code smell, this makes your data source knows too much about your system. Ideally, the process should be the opposite: the controllers know a data source and update based on the data source updates.

2022-10-19 13:22 UTC, cpradobliss commented on EmojisApp/ViewController/EmojisListViewController.swift
> +    var liveEmojiStorage: LiveEmojiStorage = .init()
Why do w need the `liveEmojiStorage` if we already have the `emojiService` object?

2022-10-19 13:22 UTC, cpradobliss commented on EmojisApp/ViewController/EmojisListViewController.swift
> +    var strong = MockedDataSource()
mocks should be injected instead of created internally, also, the name can be edited to provide a better context of what is this property

2022-10-19 13:22 UTC, cpradobliss commented on EmojisApp/ViewController/EmojisListViewController.swift
> +        let url = mockedEmojis.emojis[indexPath.row].emojiUrl
what happens if the `mockedEmojis` has fewer elements than the current `indexPath.row`?

2022-10-19 13:22 UTC, cpradobliss commented on EmojisApp/Storage/MockedEmojiStorage.swift
> +    var delegate: EmojiStorageDelegate?
this can be a `weak` property

2022-10-24 14:25 UTC, renatasiqueira commented on EmojisApp/ViewController/EmojisListViewController.swift
> +        let url = mockedEmojis.emojis[indexPath.row].emojiUrl
I think it´s gonna be a error. we need to ensure that indexPath.row it´s smaller than mockedEmojis.emojis.count. Right?

2022-10-24 14:26 UTC, renatasiqueira commented on EmojisApp/Storage/MockedEmojiStorage.swift
> +    var delegate: EmojiStorageDelegate?
Solved.

2022-10-24 14:26 UTC, renatasiqueira commented on EmojisApp/ViewController/EmojisListViewController.swift
> +    var liveEmojiStorage: LiveEmojiStorage = .init()
Solved.

2022-10-31 15:04 UTC, merged