Feature/mvvm refactor
renatasiqueira/challenge-app-ios pull request #5
Opened 2022-11-09 10:30 UTC by renatasiqueira

2022-11-16 13:12 UTC, tjanela requested changes

2022-11-16 13:12 UTC, tjanela commented on EmojisApp/Presentation/Cells/CellsCollectionView.swift
> +class CellsCollectionView: UICollectionViewCell {
Shouldn't this class be named with something ending in `CollectionViewCell`?
Furthermore, if all it does is to add an `ImageView` to a `UICollectionViewCell`, then I would name it `ImageCollectionViewCell`. What do you think?

2022-11-16 13:16 UTC, tjanela commented
Some things are named `Mocked` others are named `Mock`, I'd pick one and stick with it.
Some filenames don't match the declared class/struct/enum/protocol. It is neat to have the filename and the name of the thing within match.
Are we using the AppDelegate or the SceneDelegate to launch the app? If we are not using the AppDelegate then we should not need to have a reference to the window there.
Be sure to have at most one thing inside each file (unless it's a collection of related pointfree functions, or several extensions of an entity that make sense to be in the same file, making sure that the overall line number doesn't exceed a reasonable value, 200 to 300 should be OK). If you need to break down the extensions in several files I'd suggest using the following rule: In the case of an `extension ASimpleViewController: UITableViewDelegate`, create a new file named `ASimpleViewController+UITableViewDelegate.swift` and place the extension inside.

2022-11-21 12:13 UTC, cpradobliss approved these changes

2022-11-21 12:18 UTC, merged